# Cupcake
# Author: Chris Kempson (http://chriskempson.com)
# Converted from base16 — https://github.com/tinted-theming/base16-schemes

[general]
background   = "#FBF1F2"
text         = "#8B8198"
border       = "#D8D5DD"
accent       = "#7297B9"

[sidebar]
background   = "#F2F1F4"
text         = "#BFB9C6"
active       = "#8B8198"
unread       = "#7297B9"
mention      = "#D57E85"
server       = "#BFB9C6"

[buffer]
background   = "#FBF1F2"
timestamp    = "#BFB9C6"
server_line  = "#A59DAF"
action       = "#BB99B4"
nick_self    = "#A3B367"
separator    = "#D8D5DD"

[highlights]
mention_bg   = "#F2F1F4"
mention_text = "#D57E85"
keyword      = "#EBB790"

[nicklist]
background   = "#F2F1F4"
text         = "#BFB9C6"
op           = "#7297B9"
halfop       = "#BB99B4"
voice        = "#A3B367"
away         = "#D8D5DD"

[input]
background   = "#F2F1F4"
text         = "#8B8198"
placeholder  = "#BFB9C6"
nick_color   = "#A3B367"
