[general]
background   = "#0d0f14"
text         = "#39ff14"
border       = "#2e3c49"
accent       = "#00ffd9"

[sidebar]
background   = "#000e00"
text         = "#00bfff"
active       = "#39ff14"
unread       = "#00ffd9"
mention      = "#ff4c4c"
server       = "#1c7f0a"

[buffer]
background   = "#0d0f14"
timestamp    = "#60708b"
server_line  = "#ffd700"
action       = "#00ff99"
nick_self    = "#ff00ff"

[highlights]
mention_bg   = "#2a161a"
mention_text = "#ff4c4c"
keyword      = "#ff00ff"

[nicklist]
background   = "#000e00"
text         = "#00bfff"
op           = "#00ffd9"
halfop       = "#ff00ff"
voice        = "#00ff9d"
away         = "#007299"

[input]
background   = "#11151c"
text         = "#39ff14"
placeholder  = "#00bfff"
nick_color   = "#ff00ff"
