[general]
background   = "#37393e"
text         = "#dbdcdf"
border       = "#222326"
accent       = "#ffffff"

[sidebar]
background   = "#303236"
text         = "#9c9da2"
active       = "#dbdcdf"
unread       = "#ffffff"
mention      = "#c64f52"
server       = "#6d6e6f"

[buffer]
background   = "#37393e"
timestamp    = "#9c9da2"
server_line  = "#8e9297"
action       = "#dbdcdf"
nick_self    = "#f6b6c9"

[highlights]
mention_bg   = "#483b40"
mention_text = "#c64f52"
keyword      = "#72767d"

[nicklist]
background   = "#303236"
text         = "#9c9da2"
op           = "#ffffff"
halfop       = "#72767d"
voice        = "#509f69"
away         = "#5d5e61"

[input]
background   = "#404449"
text         = "#dbdcdf"
placeholder  = "#9c9da2"
nick_color   = "#f6b6c9"
