[general]
background   = "#1f1f28"
text         = "#dcd7ba"
border       = "#2a2a37"
accent       = "#957fb8"

[sidebar]
background   = "#1f1f28"
text         = "#727169"
active       = "#dcd7ba"
unread       = "#957fb8"
mention      = "#e46876"
server       = "#6e6b5d"

[buffer]
background   = "#1f1f28"
timestamp    = "#7e9cd8"
server_line  = "#d27e99"
action       = "#7fb4ca"
nick_self    = "#98bb6c"

[highlights]
mention_bg   = "#362731"
mention_text = "#e46876"
keyword      = "#957fb8"

[nicklist]
background   = "#1f1f28"
text         = "#727169"
op           = "#957fb8"
halfop       = "#957fb8"
voice        = "#98bb6c"
away         = "#44433f"

[input]
background   = "#363646"
text         = "#dcd7ba"
placeholder  = "#727169"
nick_color   = "#98bb6c"
