[general]
background   = "#161616"
text         = "#f2f4f8"
border       = "#262626"
accent       = "#be95ff"

[sidebar]
background   = "#161616"
text         = "#525252"
active       = "#f2f4f8"
unread       = "#be95ff"
mention      = "#ee5396"
server       = "#797a7c"

[buffer]
background   = "#161616"
timestamp    = "#393939"
server_line  = "#ff7eb6"
action       = "#3ddbd9"
nick_self    = "#42be65"

[highlights]
mention_bg   = "#2f1d25"
mention_text = "#ee5396"
keyword      = "#be95ff"

[nicklist]
background   = "#161616"
text         = "#525252"
op           = "#be95ff"
halfop       = "#be95ff"
voice        = "#42be65"
away         = "#313131"

[input]
background   = "#1f1e1e"
text         = "#f2f4f8"
placeholder  = "#525252"
nick_color   = "#42be65"
