[general]
background   = "#f4ede8"
text         = "#985C59"
border       = "#dfdad9"
accent       = "#ea9d34"

[sidebar]
background   = "#f4ede8"
text         = "#945E5F"
active       = "#d7827e"
unread       = "#ea9d34"
mention      = "#b4637a"
server       = "#6b413f"

[buffer]
background   = "#f4ede8"
timestamp    = "#cecacd"
server_line  = "#ea9d34"
action       = "#56949f"
nick_self    = "#d7827e"
separator    = "#dfdad9"

[highlights]
mention_bg   = "#ecdcda"
mention_text = "#b4637a"
keyword      = "#907aa9"

[nicklist]
background   = "#f4ede8"
text         = "#945E5F"
op           = "#ea9d34"
halfop       = "#907aa9"
voice        = "#56949f"
away         = "#484658"

[input]
background   = "#faf4ed"
text         = "#9E5F5C"
placeholder  = "#797593"
nick_color   = "#d7827e"
